version: "v1.0"
name: Production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: "Deploy to Production"
    task:
      secrets:
        - name: github-keypair
        - name: public-keys
        - name: PROD
      jobs:
      - name: Deploy Docs
        commands:
          - checkout
          - git log -1 --pretty=%B | sed '/Merge pull/d' | sed '/^\s*$/d' | tr '\n' ' ' > /tmp/commit_message
          - echo -n $PRIVATE_KEY | base64 --decode > ~/.ssh/id_rsa
          - chmod 400 ~/.ssh/id_rsa
          - git clone $PROD_REPO /tmp/prod
          - cd /tmp/prod
          - make docs.deploy
